version: 2

models:
  - name: listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primari key for listing
        tests:
          - unique
          - not_null
      
      - name: host_id
        description: Host Id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      
      - name: room_type
        description: '{{ doc("room_type_doc") }}'
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
